name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run your tests in parallel
        run: pytest -n auto --tracing=retain-on-failure

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/

      - name: Upload screenshots from failed tests
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-screenshots
          path: screenshots/